kind = "web"
previewPath = "/"
title = "E-SERVICES"
version = "1.0.0"
id = "artifacts/e-services"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21930

[services.development]
run = "pnpm --filter @workspace/e-services run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/e-services", "run", "build" ]
publicDir = "artifacts/e-services/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21930"
BASE_PATH = "/"
